"""Python side of the slug parity contract (xrepo-05).

The slug is the universal join key across the backend->site bridge (entity->report,
evidence cited-by, /heimildir/{id}/ links). It is generated by Python icelandic_slugify
and mirrored by a hand-ported JS `isSlug` in esbvaktin-site/eleventy.config.js. The same
committed fixture is asserted here AND by a Node test in the site repo, so the two
cannot drift without a test failing in one repo or the other.
"""

import json
from pathlib import Path

from esbvaktin.utils.slugify import icelandic_slugify

FIXTURE = Path(__file__).parent / "fixtures" / "slug_parity.json"


def test_canonical_slugify_matches_parity_fixture():
    cases = json.loads(FIXTURE.read_text(encoding="utf-8"))
    assert cases, "fixture must not be empty"
    for case in cases:
        assert icelandic_slugify(case["input"]) == case["slug"], case["input"]
