"""Evidence seeding pipeline — inserts JSON seed files into PostgreSQL.

Evidence JSON files are generated by Claude Code subagents (not API calls).
This script handles parsing, validation, embedding, and insertion.

Usage:
    # Insert all seed files:
    uv run python scripts/seed_evidence.py insert data/seeds/

    # Insert a single seed file:
    uv run python scripts/seed_evidence.py insert data/seeds/legal_eea.json

    # Show database summary:
    uv run python scripts/seed_evidence.py status
"""

import json
import sys
from datetime import date
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

from esbvaktin.ground_truth import (
    EvidenceEntry,
    get_connection,
    get_topic_counts,
    get_total_count,
    init_schema,
    insert_evidence,
)


def insert_from_json(json_path: Path) -> int:
    """Insert evidence entries from a JSON file into the database."""
    conn = get_connection()
    init_schema(conn)

    data = json.loads(json_path.read_text())
    if isinstance(data, dict):
        data = [data]

    count = 0
    for raw_entry in data:
        # Handle date fields
        for date_field in ("source_date", "last_verified"):
            if date_field in raw_entry and isinstance(raw_entry[date_field], str):
                try:
                    raw_entry[date_field] = date.fromisoformat(raw_entry[date_field])
                except (ValueError, TypeError):
                    raw_entry[date_field] = None
            elif date_field not in raw_entry:
                if date_field == "last_verified":
                    raw_entry[date_field] = date.today()

        try:
            entry = EvidenceEntry(**raw_entry)
            insert_evidence(entry, conn=conn)
            print(f"  ✓ {entry.evidence_id}: {entry.statement[:60]}...")
            count += 1
        except Exception as e:
            eid = raw_entry.get("evidence_id", "?")
            print(f"  ✗ {eid}: {e}")

    conn.close()
    return count


def show_status() -> None:
    """Print database summary."""
    conn = get_connection()
    total = get_total_count(conn)
    topics = get_topic_counts(conn)

    print(f"Total entries: {total}")
    if topics:
        print("\nBy topic:")
        for topic, count in topics.items():
            print(f"  {topic}: {count}")

    # Check for missing embeddings
    null_embeddings = conn.execute(
        "SELECT COUNT(*) FROM evidence WHERE embedding IS NULL"
    ).fetchone()[0]
    if null_embeddings > 0:
        print(f"\n⚠ {null_embeddings} entries missing embeddings")
    elif total > 0:
        print(f"\n✓ All {total} entries have embeddings")

    conn.close()


def main() -> None:
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    command = sys.argv[1]

    if command == "insert":
        if len(sys.argv) < 3:
            print("Usage: seed_evidence.py insert <path>")
            sys.exit(1)

        path = Path(sys.argv[2])
        if path.is_dir():
            json_files = sorted(path.glob("*.json"))
            if not json_files:
                print(f"No JSON files found in {path}")
                sys.exit(1)
            total = 0
            for f in json_files:
                print(f"\nInserting from {f.name}...")
                total += insert_from_json(f)
            print(f"\n✓ Inserted {total} entries total")
        elif path.is_file():
            count = insert_from_json(path)
            print(f"\n✓ Inserted {count} entries")
        else:
            print(f"Path not found: {path}")
            sys.exit(1)

        show_status()

    elif command == "status":
        show_status()

    else:
        print(f"Unknown command: {command}")
        print(__doc__)
        sys.exit(1)


if __name__ == "__main__":
    main()
